### PR TITLE
Updated French translation

### PR DESCRIPTION
**Pull request by rene-coty**
I updated the fr.po file

PS : running Eyedropper in GNOME Builder to check the new translations to add, I noticed that icons were missing in the preferences panel (see screenshot below).. Is this bug due to GNOME Builder ?
 
Capture d’écran du 2022-12-16 23-06-08-min

### CODE REVIEW

**Comment by FineFindus** [comment]
Thanks! I've found a few unnecessary spaces, for example `Copié :`, but I will fix them myself.

Are you using a custom icon theme? It should look like this.
App with icons

**Comment by rene-coty** [comment]
> Thanks! I've found a few unnecessary spaces, for example `Copié :`, but I will fix them myself.

If you are talking about the space between the 'Copié' and ':' it is normal, in French we always put a space between words and punctuation ;)
 
> Are you using a custom icon theme? It should look like this.

No (at least for what I'm aware of), I simply use Fedora 37 with GNOME 43 on it and usually I don't encounter issues with libadwaita apps...

**Comment by FineFindus** [comment]
> If you are talking about the space between the 'Copié' and ':' it is normal, in French we always put a space between words and punctuation ;)

Oh, interesting. I had a few years of french class and never learned that. Thanks for letting me know.

> No (at least for what I'm aware of), I simply use Fedora 37 with GNOME 43 on it and usually I don't encounter issues with libadwaita apps...

Hmm… could you please open a separate issue for it?

**Comment by rene-coty** [comment]
> Oh, interesting. I had a few years of french class and never learned that. Thanks for letting me know.

(That rule only applies when typing on a keyboard, not with manual writing)

> Hmm… could you please open a separate issue for it?

Okay

**Pull request merged**
