### PR TITLE
Update "README.md" with Weblate translation percentage

### PR DESCRIPTION
**Pull request by milotype**

### CODE REVIEW

**Comment by FineFindus** [comment]
Thanks, but I don't think a single percentage value on top of the README provides much value.

**Comment by milotype** [comment]
@FineFindus. It's up to you of course to decide … but many projects use it next to other links in the README file (in your case GNOME Circle, maintenance-status and CI), so I thought it would be a usefull information.
Cheers,

**Comment by FineFindus** [comment]
I'm just not sure what the benefit of including it is, e.g. does it help potential translators decide to contribute?
The CI status should probably be removed, it was added because GitHub didn't used to show the CI status next to the commit hash, so it was a quick way to check if the CI failed.

**Comment by milotype** [comment]
@FineFindus 
> I'm just not sure what the benefit of including it is, e.g. does it help potential translators decide to contribute? 

In my opinion yes, it does help. It shows potenitial translators upfront, that the app/project is translatable via the translation platform "Hosted Weblate".

The button is a link to quickly reach the Weblate translation platform to translate components of a project (similar to the importance of the links to the GNOME Circle and the maintenance-status). Many README files are very long and one has to scroll through the whole page to maybe find some information about translations (some projects don't even have translation files at all).

So translators with some basic programming knowledge (like me), as well as programmers who contribute to translation files via GitHub benefit, because they don't have to fork the project, create a branch, commit changes and then send a pull request. Instead they can translate via a translation platform. IMO, much easier.

About the CI status I don't have an opinion as I'm not a programmer, but I see that you have removed it.

Cheers,

**Comment by FineFindus** [comment]
No need to ping me every time, I get a notification from your comment anyway :)
I'm still not super convinced, it seems to me that it's more about having a link directly visible, in which case it might be better to just link directly to the contribution section of the README (which already links to Weblate), though since it's not overly long it feels a bit unnecessary. Will have to think about that.

**Comment by milotype** [comment]
Sorry about pinging you. I simply wanted to make sure you get my message.

IMO, one click/a direct link to the translation platform is better than letting users go through the README file (no matter how long it is) in order to find informations about translation options.

As mentioned before, it's up to you what you think is better. :-)

**Pull request closed without merging**
