### PR TITLE
Add Italian translator

### PR DESCRIPTION
**Pull request by phaerrax**
Reviewed by the Italian Translation Project <tp@lists.linux.it>.
I'm willing to keep it up to date in the future.

### CODE REVIEW

**Comment by FineFindus** [comment]
Thanks! Could you update it to the latest commit? Your version is behind it and new strings were added.

**Comment by phaerrax** [comment]
Sure :-) I didn't notice.
I have a question, too: are you open to the app name being translated? It's a common name, and the color-picker function is usually translated in other software (e.g. Adobe Photoshop, MS Office but also open-source ones) as "Contagocce", which is also the name of the physical tool depicted in the icon. There's some discussion in the translation group on whether to translate it or not, so I'd like to hear your opinion on this.

**Comment by FineFindus** [comment]
I usually leave it open to the translator. I think as long as it is a short name (it should fit in the window title, the default window is relatively small), which is connected to the physical item it should be fine.

**Comment by FineFindus** [comment]
Thanks!

**Pull request merged**
