### PR TITLE
feat(translations/russian): update translation

### PR DESCRIPTION
**Pull request by daudix-UFO**

### CODE REVIEW

**Comment by FineFindus** [comment]
Thanks, for the updated translations, you were actually too fast, I was just in the process of adding a few more :)

Please include them as well.

**Comment by daudix-UFO** [comment]
I hurried to make sure the translation will land before the release :D

**Comment by FineFindus** [comment]
Great, I just implemented the last changes with new translations, so there should be no new strings to translate. Usually I try to leave more time between release and string freeze, but this release is special in that regard.

Usually I email all current translator when I finished and they can start. If you want to be included as well, please add yourself with your email-address as the `Last-Translator`.

**Comment by daudix-UFO** [comment]
The translation is updated to the latest `.pot`

**Comment by FineFindus** [comment]
Thanks!

**Comment by daudix-UFO** [comment]
Btw, congratulations on joining gnome circle!

Love your app, use it on daily basis and it is awesome 🔥

**Comment by FineFindus** [comment]
Thanks, I'm super excited about it. How did you know this early, there has been an announcement yet? 

Nice to hear that the app is used by others and I'm not just coding into the void, let me know if you have any feedback.

**Comment by daudix-UFO** [comment]
> How did you know this early, there has been an announcement yet?

I go to Circle app submissions from time to time and saw eyedropper there, then today I saw it being on apps.gnome.org and thought that I need to hurry with translation :P

**Pull request merged**
