### PR TITLE
Update all .po files

### PR DESCRIPTION
**Pull request by milotype**
- changed the first section of the header for every language to make them more uniform
- updated all .po files with the current .pot file, so now all files have 153 strings
- deleted all old/obsolete strings
- added string translations in obvious cases without knowing/speeking all languages. For instance: if the string "RGB Format" existed, I added translations for the new strings "Oklab Format", "Oklch Format" according to the translation for "RGB Format". In the case of "Copy Oklab" and "Copy Oklch", I used the same translation for the word "Copy" as in "Copy RGB" used in the specific language.
- added "translations" for the strings "Oklab" and "Oklch"
- the spanish translation is based upon the not yet released version of the user "IngrownMink4" (PR Update es.po #84)
- changed the "Eyedropper" app name in the Croatian translation ("Pipeta" is better then "Kapaljka")

### CODE REVIEW

**Review by FineFindus — CHANGES_REQUESTED** [review]
Sorry for the late reply, I have been a bit busy with other things.
The changes look good, but due to the total amount, please separate them into individual commits, following [conventional commits](https://www.conventionalcommits.org), e.g. `feat(po/de): remove obsolete strings`.
This makes it easier for future contributors to see what and why a change was made.
> added "translations" for the strings "Oklab" and "Oklch"

I'm not sure what you mean by this.

Please request a review when you are done.

**Comment by milotype** [comment]
@FineFindus
In future I will make separate commits, I promise :-)

But in this case I've done several changes in all .po files at once per GitHub, because the component [Eyedropper](https://hosted.weblate.org/projects/eyedropper/) at Hosted Weblate is currently locked for all languages.

Maybe you can merge my changes for all files in this commit nevertheless and then apply them in Hosted Weblate?!
I'm not a programmer, so I don't really know about the procedures between GitHub and Hosted Weblate :-(

> I'm not sure what you mean by this.

Concearning my message: **added "translations" for the strings "Oklab" and "Oklch"**
```
#: src/widgets/preferences/preferences_window.rs:413
msgid "Oklab"
msgstr "Oklab"
```
```
#: src/widgets/preferences/preferences_window.rs:414
msgid "Oklch"
msgstr "Oklch"
```
It means that I've simply copied those two strings unchanged in every .po language file, because the source strings shouldn't be tanslated.

Please also check my isue #105.

**Comment by FineFindus** [comment]
Sorry, but I'm not going to merge this as a single commit. You can use `git reset --soft HEAD~1` to reset the entire commit and then commit again, or use `git rebase --interactive HEAD~1`.

**Comment by milotype** [comment]
Sorry, I'm not a programmer (just a translator) and I don't know how to do what you suggest. :-((
Can you or someone else maybe do what is needed to resolve it?
I think the project would benefit if my changes would be merged.

**Review by FineFindus — APPROVED** [review]

**Comment by FineFindus** [comment]
Thanks.

**Pull request merged**
